#!/usr/bin/env python
# coding: utf-8

# ## Air quality forecast secondary modeling
# 
# Atmospheric pollution refers to the fact that certain substances enter the atmosphere due to human activities or natural processes, present a sufficient 
# concentration, reach a sufficient time, and therefore endanger the comfort, health and welfare of the human body or endanger the ecological environment. 
# Pollution prevention and control practices have shown that establishing an air quality forecast model, knowing the process of air pollution that may occur 
# in advance and taking corresponding control measures are one of the effective ways to reduce the harm caused by air pollution to human health and the 
# environment, and to improve ambient air quality.

%config InlineBackend.figure_format = 'retina'
%matplotlib inline    
import seaborn as sns 
sns.set(font= "Kaiti",style="ticks",font_scale=1.4)
import matplotlib
matplotlib.rcParams['axes.unicode_minus']=False # Solve the display problem of the negative sign of the coordinate axis
## Import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno 
import plotly.express as px
from sklearn.cluster import *
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.manifold import TSNE

# ## Question 1
# Using the data in Annex 1, calculate the AQI and primary pollutants measured daily at monitoring point A from August 25 to August 28, 2020 according to 
# the method in the appendix

## Read the data to be calculated
usedf = pd.read_excel("Data for Question 1.xlsx")
usedf.head()

## Delete the last three rows of data in the data first
usedf.tail()

usedf = usedf.iloc[0:-3,:]
usedf.tail()










