#!/usr/bin/env python
# coding: utf-8

%config InlineBackend.figure_format = 'retina'
%matplotlib inline    
import seaborn as sns 
sns.set(font= "Kaiti",style="ticks",font_scale=1.4)
import matplotlib
matplotlib.rcParams['axes.unicode_minus']=False # Solve the display problem of the negative sign of the coordinate axis
## Import the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import missingno as msno 
import plotly.express as px
from sklearn.cluster import *
from sklearn.metrics import *
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.manifold import TSNE

# ## Question 3
# Using the data in Annexes 1 and 2, establish a secondary forecasting mathematical model that is applicable to three monitoring points A, B, and C 
# at the same time (the distance between the two monitoring points is more than 100km, ignoring the mutual influence) to predict the future three The 
# single-day concentration values of 6 conventional pollutants in a day require that the maximum relative error of the AQI forecast value in the prediction 
# results of the secondary forecast model should be as small as possible, and the accuracy of the primary pollutant forecast should be as high as possible. 
# And use the model to predict the single-day concentration values of 6 conventional pollutants at monitoring points A, B, and C from July 13 to July 15, 2021, 
# and calculate the corresponding AQI and primary pollutants.
